# Generated by Django 3.2.5 on 2021-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='dwelling_area',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
