# Generated by Django 3.2.5 on 2021-07-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20210725_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='dwelling_area',
            new_name='dwelling_type',
        ),
    ]
